apiVersion: 1

datasources:
  - name: TEA-Prometheus
    uid: tea-prometheus
    type: prometheus
    access: proxy
    url: http://tea-prometheus:9090
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
